stages:
  - build
  - qa
  - distribution
  - sdk
  - sdk_test

building:linux:
  stage: build
  image: gitlab.ta.philips.com:5432/forest/docker/centos-ci:0.2.0
  script:
    - ./ci/bin/build.sh
  tags:
    - docker
  artifacts:
    paths:
      - ./build/*

#sonar:
#  stage: qa
#  image: gitlab.ta.philips.com:5432/forest/docker/centos-ci:latest
#  script:
#    - ./ci/bin/code_coverage.sh
#    - ./ci/bin/static_code_analysis.sh
#    - ./ci/bin/memory_leak_detection.sh xml
#    - sonar-scanner -Dsonar.login=${SONAR_LOGIN}  -Dsonar.host.url=https://sonar.ta.philips.com/
#  tags:
#    - docker
#  dependencies:
#    - building:linux

testing_lib:linux:
  stage: qa
  image: gitlab.ta.philips.com:5432/forest/docker/centos-ci:0.2.0
  script:
    - ./ci/bin/unittests.sh
  tags:
    - docker
  dependencies:
    - building:linux

distribution:linux:
  stage: distribution
  image: gitlab.ta.philips.com:5432/forest/docker/centos-ci:0.2.0
  script:
    - ./ci/bin/mk_os_distribution.sh
  tags:
    - docker
  artifacts:
    paths:
      - ./build/Linux/dist
  dependencies:
    - building:linux

building:windows:
  stage: build
  script:
    - .\ci\bin\build.bat
  tags:
    - windows
  artifacts:
    paths:
      - .\build\*

testing_lib:windwows:
  stage: qa
  script:
    - .\ci\bin\unittests.bat
  tags:
    - windows
  dependencies:
    - building:windows

distribution:windows:
  stage: distribution
  script:
    - .\ci\bin\mk_os_distribution.bat
  tags:
    - windows
  artifacts:
    paths:
      - .\build\Windows\dist
  dependencies:
    - building:windows

sdk:
  stage: sdk
  image: gitlab.ta.philips.com:5432/forest/docker/centos-ci:0.2.0
  script:
    - ./ci/bin/mksdk.sh
  tags:
    - docker
  dependencies:
    - distribution:windows
    - distribution:linux
  artifacts:
    paths:
      - ./dist

sdk_test:windows:
  stage: sdk_test
  script: |
    cd dist\IUS-SDK*
    bin\unittests.bat

  tags:
    - windows
  dependencies:
    - sdk

sdk_test:linux:
  stage: sdk_test
  image: gitlab.ta.philips.com:5432/forest/docker/centos-ci:0.2.0
  script: |
    cd dist/IUS-SDK*
    bin/unittests.sh
    
  tags:
    - docker
  dependencies:
    - sdk