language: C

env:
  - HDF5_ROOT=./Download/hdf5

os: windows
cache:
  directories:
    - Download

before_install:
  - cmake --version
  - ci/bin/install.bat %HDF5_ROOT%

jobs:
  include:
    - stage: build
      script:
        - ci/bin/build.bat
    - stage: test
      script:
        - ci/bin/unittest.bat
    - stage: distribution
      script:
        - ci/bin/mk_os_distribution.bat
