language: C

os: windows
cache:
  directories:
    - Downloads

before_install:
  - pwd
  - mkdir ./Downloads
  - curl -L -0 -J https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8/hdf5-1.8.20/bin/windows/hdf5-1.8.20-Std-win7_64-vs14.zip -o ./Downloads/hdf5-1.8.20-Std-win7_64-vs14.zip
  - mkdir ./Downloads/HDF5
  - 7z x ./Downloads/hdf5-1.8.20-Std-win7_64-vs14.zip -o./Downloads/HDF5

script:
  - dir
