language: C

cache:
  timeout: 1800  # 30 mins
  directories:
    - Download
    - build

stages:
  - build
  - test
  - distribution

os:
#  - windows
  - linux

dist: bionic

#matrix:
#  include:
#  - os: linux
#    env:
#      - MATRIX_EVAL="HDF5_ROOT="
#  - os: windows
#    env:
#      - MATRIX_EVAL="HDF5_ROOT=./Download/hdf5"

before_install:
  - ci/bin/travis.sh before_install

jobs:
  include:
    - stage: build
      script:
        - ci/bin/travis.sh build
    - stage: test
      script:
        - ci/bin/travis.sh test
    - stage: distribution
      script:
        - ci/bin/travis.sh dist
