language: C


matrix:
  include:
    - os: windows
      env:
        - HDF5_ROOT=./Download/hdf5

  #    - os: linux
#      dist: bionic

#os:
#  - linux
#  - windows
#  env:
#    - HDF5_ROOT=./Download/hdf5

#  - linux
 # - osx

# cache:
#   directories:
#     - Download

before_install:
  - ci/bin/travis.sh before_install

jobs:
  include:
    - stage: build
      script:
        - ci/bin/travis.sh build 
    - stage: test
      script:
        - ci/bin/travis.sh test 
    - stage: distribution
      script:
        - ci/bin/travis.sh dist 
