language: C

env:
  - HDF5_ROOT=./Download/hdf5

os: 
 # - osx
 # - windows
  - linux
    dist: bionic

# cache:
#   directories:
#     - Download

before_install:
  - ci/bin/travis.sh before_install

jobs:
  include:
    - stage: build
      script:
        - ci/bin/travis.sh build 
    - stage: test
      script:
        - ci/bin/travis.sh test 
    - stage: distribution
      script:
        - ci/bin/travis.sh dist 
