language: C

env:
  - HDF5_ROOT=.\Download\hdf5

os: windows
cache:
  directories:
    - Download

before_install:
  - cmake --version
  - ci/bin/install.bat %HDF5_ROOT%

script:
  - ci/bin/build.bat
