language: C

os: windows
cache:
  directories:
    - Download

before_install:
  - cmake --version
  - where h5dump
  - ci/bin/install_vcpkg.bat
  - where h5dump
  - dir C:\Program Files\

script:
  - ci/bin/build.bat
