language: C

notifications:
  slack:
    secure: s8BNZHPiw7N6B19mWbv9JG73opIi3ltiUeWl3BVpC7SbRDnDfnXNA+tM7u5+r5OMSGJgXdiiPSM8O+82Zasi+1gVdOy59PRQMHZvbw+3yMN8HNMMreF//n3JXrerbQJk4O1taamwI+Y4W530M1tvWnM95e+kAp45vPyQFxnQr5L8R6pDzsrVx5T6ZS4zk4MSI7FwSTEoZrjZQz5GV8lbxEWMFe05zK5a+0x63whNsD/IeXYw0MKX348yHH0SWH4lVNALK8zyvQe/Z1TV1OsOjpTp6mmgL8k4brEWLkHuBQTfB1C+V0NyyMXIH2V463/ntxd1tbfnce/bchTkTK9NhKqsp5rHUKxEWVbRcnc4k/T6+SG/MXFKdHHQcGQDyt4hoD9lmDUdGZDkc9+largi7eQyVA1MAIKI4UQofXojLy1NJq1cy4gYkluD45XMCa7rtvLMqAJ859O4cC1A9EwzArdyoMc9j8cnRKs1WhfJdKY884f3Coz5GW+oacJNxrL2YYn8nawmaz6LChJuHvffMZ+vWxcpA7RKfc3NnsVuNN48hrtarpeFTc0b7U7MqEcFyQUuTcpO7EjYw9b2uyEdva4GykzxF4pw+0Cn1THaRDIOe7znibcFv4cqLM8+Th5+S0aWORfkbvtiKqkLJlyKyBMj3P5TRVloXlDV/XVzxbs=

cache:
  timeout: 3600  # 60 mins
  directories:
    - Download
    - build

stages:
  - build
  - test
  - qa

dist: bionic

addons:
  sonarcloud:
    organization: philips-software
    token:
      secure: "dkv2QfPmDyEqXFH4hmv6W8uSR8cQ+3yUrKxWxwasMFOlXTyctWBrrWQ7HYWzqkBSGnR8UQqKL+0Sr2uiI1CbXTPVSBxro1w9qfBcUSfa79UqSFN0xXOTYFQFbNmhq568nsLtNESCjNez9LsPqJG1FBHQk1guEVCaKcoRJyfgj0IjpJ409NDoCnXAolEr9FHeUXPPZpaRtVvScgjj9SwE+Qy6DAU1G9sGSys/pkrkF6G3X2ho+rXTDZjkMy82rM6I9ABeeTU2LzAwqJAzlArVK9167gcpf/zuiiM0nGdnM2M/JYPEXMaTgULCMI/5Sp9TkRWxt5F9C5z+mvvuJSm96r7PK0ieg8fWoEYY6tvFGhOQnQCfnVzhGqLh/OWG1h6P46dSVQ2Yqo1CruEclucwD/9FT2LF+At/Db3rD8HAy1r47+MirTsRHK6FtiHbJiUTp2BsB7R9JTKTyYx+6jgG5XUTiljR716DJ+ABOzX6i6iBkjDroL4h3SEQDfWjsRgHFASaJnHQAPOtmBEcIZRM6tX2OioPtIfF/t1PAHirFPl0PxErJOa1CwMr+KG37NDhFw9OVB8e9eFrN7+dUryoOL97Nu8T5Ob/QlTfUm0SmJzKUaByC9KJ6cz+h62OIn12NwYQdikDKPuQ8Zg1HsxkAuN98fQi5NgrLjPIlWzlFRo="

env:
  CMAKE_BUILD_PARALLEL_LEVEL=4

before_install: ci/bin/travis.sh before_install

jobs:
  include:
    - stage: build
      name: "MacOS build"
      os: osx
      osx_image: xcode11
      script: ./ci/bin/travis.sh build
    - stage: test
      name: "MacOS test"
      os: osx
      script: ./ci/bin/travis.sh test
    - stage: build
      name: "Linux build"
      os: linux
      script: ./ci/bin/travis.sh build
    - stage: test
      name: "Linux test"
      os: linux
      script: ./ci/bin/travis.sh test
    - stage: qa
      name: "QA step (Linux only)"
      os: linux
      script: ./ci/bin/travis.sh qa
    - stage: build
      name: "Windows build"
      os: windows
      env: HDF5_ROOT=./Download/hdf5
      script: ./ci/bin/travis.sh build
    - stage: test
      name: "Windows test"
      os: windows
      env: HDF5_ROOT=./Download/hdf5
      script: ./ci/bin/travis.sh test
