language: C

os:
  - windows
  - linux

env:
  - HDF5_ROOT=./Download/hdf5

cache:
  timeout: 1800  # 30 mins
  directories:
    - Download
    - build

matrix:
  include:
    - os: windows
    - os: linux
      dist: bionic

  before_install:
    - ci/bin/travis.sh before_install

  jobs:
    include:
      - stage: build
        script:
          - ci/bin/travis.sh build
      - stage: test
        script:
          - ci/bin/travis.sh test
      - stage: distribution
        script:
          - ci/bin/travis.sh dist
