language: C

cache:
  timeout: 1800  # 30 mins
  directories:
    - Download
    - build

stages:
  - build
  - qa
  - distribution

dist: bionic

os:
  - linux
  - windows

matrix:
  include:
  - name: "Linux pipeline"
    os: linux
    env:
      - HDF5_ROOT=
  - name: "Windows pipeline"
    os: windows
    env:
      - HDF5_ROOT=./Download/hdf5

before_install: ci/bin/travis.sh before_install

jobs:
  include:
    - stage: build
      script: ./ci/bin/travis.sh build
    - stage: qa
      script: ./ci/bin/travis.sh test
    - stage: distribution
      script: ./ci/bin/travis.sh dist