language: C
notifications:
  slack:
    rooms:
    - secure: s8BNZHPiw7N6B19mWbv9JG73opIi3ltiUeWl3BVpC7SbRDnDfnXNA+tM7u5+r5OMSGJgXdiiPSM8O+82Zasi+1gVdOy59PRQMHZvbw+3yMN8HNMMreF//n3JXrerbQJk4O1taamwI+Y4W530M1tvWnM95e+kAp45vPyQFxnQr5L8R6pDzsrVx5T6ZS4zk4MSI7FwSTEoZrjZQz5GV8lbxEWMFe05zK5a+0x63whNsD/IeXYw0MKX348yHH0SWH4lVNALK8zyvQe/Z1TV1OsOjpTp6mmgL8k4brEWLkHuBQTfB1C+V0NyyMXIH2V463/ntxd1tbfnce/bchTkTK9NhKqsp5rHUKxEWVbRcnc4k/T6+SG/MXFKdHHQcGQDyt4hoD9lmDUdGZDkc9+largi7eQyVA1MAIKI4UQofXojLy1NJq1cy4gYkluD45XMCa7rtvLMqAJ859O4cC1A9EwzArdyoMc9j8cnRKs1WhfJdKY884f3Coz5GW+oacJNxrL2YYn8nawmaz6LChJuHvffMZ+vWxcpA7RKfc3NnsVuNN48hrtarpeFTc0b7U7MqEcFyQUuTcpO7EjYw9b2uyEdva4GykzxF4pw+0Cn1THaRDIOe7znibcFv4cqLM8+Th5+S0aWORfkbvtiKqkLJlyKyBMj3P5TRVloXlDV/XVzxbs=
    - secure: ahuOzoZAmeXwNJb+p7wUFcGthrE8o1m+4R2k6qgSM80rH8rePuUI/fLNzIGXKGMhqgs5Vc75YhFbK6jOQvNFJLbdLv3XJZZw2JNg434T3pfwuG8F0MH/HqN1MJ48VLEYCjfaJVdovHHHEUqs5MnwY2DoJhDWsEEW7K8IivirVVeXtn2oev1UapJ6mXXsNi6RNYGgsvSARcpLdTch/g8yYh6LGrxJ2ZrPIDmpdzN8oGTXmaeLr7LC1NDbcXRfN+GH9ByTDirEjOrx4llG0RGIzKWA86+o4dbbZox5VfGOuUv8rp36LWGSIt4v/zW9SWVMjWlw4JXp5L3SG4kIbhHS3nvCtW8fgVQYdoD58GYzwTzRxkR0/9+o95kqyDrLqmjhXv65LxGtjDoUxR/JlPGUmVnXtQMnAfuwqFBOJeR7EbV6s0d0preTo3W0EvlgJRmxIFSGhAqDbYg2Qhd36xoXYn/zxUu9SrxC+AoceUVSzYCLZTW1d0xPkFQXWg4/5Sphfbd5x0zey5fKbIyiespA5u+bxXYEj8h1kRFv2LVyHSc1nFNDRyorrvytUglsKGurtvg77FlkXB0vlHobr0m7IsCroZrfzK8a8xOAcLJoQ33OOo802Fmpau7EmzvkBILP6/uXMo88lCobA9RUwUrxBPsvubHiT2VHjpBGAr3AAXE=
addons:
  sonarcloud:
    organization: philips-software
    token:
      secure: rTmmFNFVzZ+Qf28CWovwBYL+aFDPO6ifWPf/xmDZcecgMwp6UtIAyI2+yt5VSjT7YBUv7NrnOR201IAmovyqw+0xwhcjkOQt+Xb6Lg2AJEt5g+k5NmU0qvNMxVQn1ZDfxQrrdJFrmd1kzFMRVDnUazC7IzZ+zrXZH3xey7RFsFSlgxYSFvjcRGsFKQu8D6pdsorVdhf7Y9mmY/dbc6Zgw1eB0HI2yX5VUCAhe51miZahJX2oNl372ECd/d24iKUwHXXnB8bg+fBmM4aQobU2ry4rWmOrc8+lIzGGmUtgcI6P16clYiqPtoTsCsnyD/HxcWRGsgneH97DanHI0ue/+O+QU9H2wPiW2i/4DR8p7b9oA2OodEHNHJOLGvWdpQglBHvFmRXdjFjoXPEqFIrHzVS38wlxkM8uMfrDmqB7Qs3Q9E06vq9KzLdcLoiE2AkEt+jOH7vvdYp5VzaRkU6ViAPK6UsCNSRGndZe+a5UlxGHxHCmlgb2HYK5gnhejeyZZIdohzB2FiISaXEXIoElj7pPz+fqDKAokzME+9WRWj6nSqnfn3fJsTgbnnlODykl5xkre4rC60pbdAxC4EaQJTb5HL4esyxxbIGJ0Kx4Bw22Jf5K5GT3cgIqOju7lNS4pJDWrsXTzGjcT5M+Fp0LA6ceQihzdsosCI89sQXoYvg=
dist: bionic
env:
  matrix:
  - CMAKE_BUILD_PARALLEL_LEVEL=4
  global:
    secure: xveQZgimJtiola4CjxLzLj53V1/PUazqVyyn6yfxPhFK2l1KywO1NxSsFSLJmIB1WdBwr50pqHVlIUKgMvc1qB+Q9SsRdN3pmjrpYHRR+AvslfnExeiUPATsYJHIZpw6NDq6RaV9JIZdWum53cy7g+uKgmzT1BljPtjTjAvimxIcT5jLbgHsu/w4gP81FM/Y8Haqn/MIKyMnae3dm1remKkB+vAXac+jqNLSlBmp74VqdHGe/WVkcqg6ARbV0mHIf5eDhkPGULGITXJA8HgqlLGEI9wiKoa/FnSJCOgxffmbsigfcFEeSkwS606aQule5MKrY6XgTuZbZzSR7CPrG2OUri310Il3CO30VsedQoez+oo0iXoq9Ub0+KI62WsoGBaVR6uj/bzk3gGr1sWafMZ12Fl9oJj7oWMptZ6bcDHo8/RTkN+Sql3fopC96zKlXigbqGcsRlceOvZuq6mluo7XheXLiWy5/sCrLn9hl66Cg9ej1DXjdnyjr2m9dKXi+w3rgs8nGjSZ/ftHhWs91/nNn3cMbiD/Bqz4XRnTP8ZZos7yHW4dJYoR7PIf7GegEIJxKIACs+hbssYhTYZqpPJCzADdHCpWjcWLMPWo9z4jX90x5YEgpo9/f5Ko4FZIubZ7ATpptxztrDcYSFuDWhmOPTFjbhXOfN0sskdACso=
stages:
- build
- test
- qa
- doc
before_install: ci/bin/travis.sh before_install
jobs:
  include:
  - stage: qa
    name: QA step (Linux only)
    os: linux
    script: "./ci/bin/travis.sh qa"
