language: C

cache:
  directories:
  - $HOME/docker-images

services:
  - docker

before_install:
- echo "Setting up build container"
- |
  if [[ ! -f $HOME/docker-images/centos-ci:0.5.2.tgz ]]
  then
    echo "Saving build container..."
    [[ ! -d $HOME/docker-images ]] && mkdir $HOME/docker-images
    docker save ruijzndl/centos-ci:0.5.2 | gzip -c > $HOME/docker-images/centos-ci:0.5.2.tgz
  fi
- |
  if [[ -f $HOME/docker-images/centos-ci:0.5.2.tgz ]]
  then
    ls -l $HOME/docker-images/
    echo "Loading build container..."
    docker load -i $HOME/docker-images/centos-ci:0.5.2.tgz
  fi
- docker run --name centos -d -v $(pwd):$(pwd) -v /var/run/docker.sock:/var/run/docker.sock -w $(pwd) ruijzndl/centos-ci:0.5.2 /bin/sh -c "while true; do sleep 1; done"
- docker ps -a

script:
- docker exec -it centos ci/bin/build.sh
