language: C

cache:
  directories:
  - $HOME/docker-images

services:
  - docker

before_install:
- docker run --name centos -d -v $(pwd):$(pwd) -v /var/run/docker.sock:/var/run/docker.sock -w $(pwd) ruijzndl/centos-ci:0.5.2 /bin/sh -c "while true; do sleep 1; done"
- docker ps -a

script:
- docker exec -it centos ci/bin/build.sh
