language: C

#os:
#  - windows
#  - linux
#
#env:
#  -
#
#cache:
#  timeout: 1800  # 30 mins
#  directories:
#    - Download
#    - build

dist: bionic

matrix:
  include:
    - os: windows
      env: HDF5_ROOT=./Download/hdf5
    - os: linux

before_install:
  - ci/bin/travis.sh before_install

jobs:
  include:
    - stage: build
      script:
        - ci/bin/travis.sh build
    - stage: test
      script:
        - ci/bin/travis.sh test
    - stage: distribution
      script:
        - ci/bin/travis.sh dist
