language: C

cache:
  timeout: 1800  # 30 mins
  directories:
    - Download
    - build

stages:
  - build
  - test
  - distribution

#os:
##  - windows
#  - linux

dist: bionic

matrix:
  include:
  - name: "Linux build"
    os: linux
    env:
      - STAGE=build
  - name: "Linux qa"
    os: linux
    env:
      - STAGE=test
  - name: "Linux dist"
    os: linux
    env:
      - STAGE=dist
  - name: "Windows build"
    os: windows
    env:
      - STAGE=build HDF5_ROOT=./Download/hdf5
  - name: "Windows qa"
    os: windows
    env:
      - STAGE=test HDF5_ROOT=./Download/hdf5
  - name: "Windows dist"
    os: windows
    env:
      - STAGE=dist HDF5_ROOT=./Download/hdf5

before_install: ci/bin/travis.sh before_install

script: ci/bin/travis.sh $STAGE

