
fnlist = {...
    'create',...
    'frameCreate',...
    'responseCreate',...
    'channelCreate',...
    'delete',...
    'nodeLoad',...
    'nodeSave',...
    'close',...
    'compare',...
    'getFrameList',...
    'getPatternListDict',...
    'getPulseDict',...
    'getSourceDict',...
    'getReceiveChannelMapDict',...
    'getTransmitApodizationDict',...
    'getReceiveSettingsDict',...
    'getAcquisition',...
    'getTransducer',...
    'getNumFrames',...
    'getNumResponses',...
    'getNumChannels',...
    'getSamplesPerLine',...
    'setFrameList',...
    'setPatternListDict',...
    'setPulseDict',...
    'setSourceDict',...
    'setReceiveChannelMapDict',...
    'setTransmitApodizationDict',...
    'setReceiveSettingsDict',...
    'setAcquisition',...
    'setTransducer',...
    'channelSave',...
    'channelLoad',...
    'responseSave',...
    'responseLoad',...
    'frameSave',...
    'frameLoad'...
    };

for c1 = 1:length(fnlist)
    fn = fnlist{c1};
    %disp(fn);
    mxInputFile( fn );
end
