clear all;
close all;
clc;

fnlist = {...
    'create',...
    'frameCreate',...
    'responseCreate',...
    'channelCreate',...
    'delete',...
    'nodeLoad',...
    'nodeSave',...
    'close',...
    'compare',...
    'getFrameList',...
    'getPatternListDict',...
    'getPulseDict',...
    'getSourceDict',...
    'getReceiveChannelMapDict',...
    'getTransmitApodizationDict',...
    'getReceiveSettingsDict',...
    'getAcquisition',...
    'getTransducer',...
    'getNumFrames',...
    'getNumResponses',...
    'getNumChannels',...
    'getSamplesPerLine',...
    'setFrameList',...
    'setPatternListDict',...
    'setPulseDict',...
    'setSourceDict',...
    'setReceiveChannelMapDict',...
    'setTransmitApodizationDict',...
    'setReceiveSettingsDict',...
    'setAcquisition',...
    'setTransducer',...
    'channelSave',...
    'channelLoad',...
    'responseSave',...
    'responseLoad',...
    'frameSave',...
    'frameLoad'...
    };

% for c1 = 1:length(fnlist)
%     fn = fnlist{c1};
%     disp(fn);
%     mxInputFile( fn );
% end
clear all
cd('../src');
mxCreate
cd('../m');
h = mxInputFile('create', 'myInputFile.input')
h2 = mxInputFile('create', 'myInputFile2.input')
h3 = mxInputFile('create', 'myInputFile3.input')

%mxInputFile('close', h)
%mxInputFile('close', h2);
% mxInputFile('close', h3);

clear all

